// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odanraujo/financial-organizer-api/internal/usecase/users (interfaces: UserUsercase)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	excp "github.com/odanraujo/financial-organizer-api/infrastructure/excp"
	users "github.com/odanraujo/financial-organizer-api/internal/entity/users"
)

// MockUserUsercase is a mock of UserUsercase interface.
type MockUserUsercase struct {
	ctrl     *gomock.Controller
	recorder *MockUserUsercaseMockRecorder
}

// MockUserUsercaseMockRecorder is the mock recorder for MockUserUsercase.
type MockUserUsercaseMockRecorder struct {
	mock *MockUserUsercase
}

// NewMockUserUsercase creates a new mock instance.
func NewMockUserUsercase(ctrl *gomock.Controller) *MockUserUsercase {
	mock := &MockUserUsercase{ctrl: ctrl}
	mock.recorder = &MockUserUsercaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUsercase) EXPECT() *MockUserUsercaseMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserUsercase) CreateUser(arg0 context.Context, arg1 users.CreateUser) (users.CreateUser, *excp.Exception) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(users.CreateUser)
	ret1, _ := ret[1].(*excp.Exception)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserUsercaseMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserUsercase)(nil).CreateUser), arg0, arg1)
}

// GetUserForCPF mocks base method.
func (m *MockUserUsercase) GetUserForCPF(arg0 context.Context, arg1 string) (users.CreateUser, *excp.Exception) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserForCPF", arg0, arg1)
	ret0, _ := ret[0].(users.CreateUser)
	ret1, _ := ret[1].(*excp.Exception)
	return ret0, ret1
}

// GetUserForCPF indicates an expected call of GetUserForCPF.
func (mr *MockUserUsercaseMockRecorder) GetUserForCPF(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserForCPF", reflect.TypeOf((*MockUserUsercase)(nil).GetUserForCPF), arg0, arg1)
}
