name: financial organization api continuos deployment
on:
  pull_request:
    branches:
      - main
jobs:
  financial-integration-continuos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-versions: 1.x
      - name: Build and test
        run: |
          go build ./...
          go test ./... -count=1 -race -timeout=30m -shuffle=on