version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 1987:27017
    networks:
      - financialmongo_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_PORT: ${MONGO_PORT}

networks:
  financialmongo_network: