name: Financial Organization API Continuous Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  financial-integration-continuous:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.x'

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./... -count=1 -race -timeout=30m -shuffle=on